# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allume_app', '0003_auto_20180827_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styling_goal', models.CharField(max_length=500)),
                ('testimonial', models.TextField()),
            ],
        ),
    ]
